# Generated by Django 4.0.5 on 2022-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Class', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('RollNo', models.IntegerField()),
            ],
        ),
    ]
